// <auto-generated />
using KitchenRental.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KitchenRental.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230603100354_RentalKitchenDto_Identity_Column_Remove")]
    partial class RentalKitchenDto_Identity_Column_Remove
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KitchenRental.DataAccess.Models.DataTransferObjects.RentalKitchenDto", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Equipments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FloorArea")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RentPricePerMinute")
                        .HasColumnType("float");

                    b.Property<int>("Temporary_Id")
                        .HasColumnType("int");

                    b.Property<int>("WorkingArea")
                        .HasColumnType("int");

                    b.ToTable("RentalKitchens");
                });
#pragma warning restore 612, 618
        }
    }
}
