// <auto-generated />
using System;
using KitchenRental.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KitchenRental.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230723103659_Add_Equipment_Model")]
    partial class Add_Equipment_Model
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KitchenRental.DataAccess.Models.DataTransferObjects.EquipmentDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RentalKitchenDtoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RentalKitchenDtoId");

                    b.ToTable("EquipmentDto");
                });

            modelBuilder.Entity("KitchenRental.DataAccess.Models.DataTransferObjects.RentalKitchenDto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FloorArea")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RentPricePerMinute")
                        .HasColumnType("float");

                    b.Property<int>("WorkingArea")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RentalKitchens");
                });

            modelBuilder.Entity("KitchenRental.DataAccess.Models.DataTransferObjects.EquipmentDto", b =>
                {
                    b.HasOne("KitchenRental.DataAccess.Models.DataTransferObjects.RentalKitchenDto", null)
                        .WithMany("Equipments")
                        .HasForeignKey("RentalKitchenDtoId");
                });

            modelBuilder.Entity("KitchenRental.DataAccess.Models.DataTransferObjects.RentalKitchenDto", b =>
                {
                    b.Navigation("Equipments");
                });
#pragma warning restore 612, 618
        }
    }
}
